spring:
  h2:
    console:
      enabled: true
  datasource:
#    username: sa
#    password:
    url: jdbc:h2:mem:testdb
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true  # sql 보이도록 설정
